plugins {
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

repositories {
    mavenCentral()
}

version = projectVersion
group = 'io.github.mlangc'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

gradlePlugin {
  website.set('https://github.com/mlangc/gradle-jmh-report')
  vcsUrl.set('https://github.com/mlangc/gradle-jmh-report')

  plugins {
    jmhReportPlugin {
      id = 'io.github.mlangc.jmhreport'
      implementationClass = 'io.github.mlangc.jmhreport.gradle.JmhReportPlugin'
      displayName = 'JMH Report plugin'
      description = 'A Gradle plugin building a visual report on top of your JMH benchmark results!'
      tags.set(['jmh', 'report', 'visualization'])
      compatibility(it) {
        features {
          configurationCache.set(true)
        }
      }
    }
  }
}

publishing {
  publications {
    pluginMaven(MavenPublication) {
      pom {
        name.set('JMH Report plugin')
        description.set('A Gradle plugin building a visual report on top of your JMH benchmark results!')
        url.set('https://github.com/mlangc/gradle-jmh-report')
        licenses {
          license {
            name.set('The Apache License, Version 2.0')
            url.set('https://www.apache.org/licenses/LICENSE-2.0.txt')
          }
        }
        scm {
          url.set('https://github.com/mlangc/gradle-jmh-report')
          connection.set('scm:git:https://github.com/mlangc/gradle-jmh-report.git')
          developerConnection.set('scm:git:git@github.com:mlangc/gradle-jmh-report.git')
        }
      }
    }
  }
}
