plugins {
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

repositories {
    mavenCentral()
}

version = projectVersion
group = 'com.github.mlangc'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

gradlePlugin {
  website.set('https://github.com/mlangc/gradle-jmh-report')
  vcsUrl.set('https://github.com/mlangc/gradle-jmh-report')

  plugins {
    jmhReportPlugin {
      id = 'com.github.mlangc.jmhreport'
      implementationClass = 'com.github.mlangc.jmhreport.gradle.JmhReportPlugin'
      displayName = 'JMH Report plugin'
      description = 'A Gradle plugin building a visual report on top of your JMH benchmark results!'
      tags.set(['jmh', 'report', 'visualization'])
    }
  }
}
