plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
    id 'org.jetbrains.kotlin.kapt' version '2.4.20'
}
apply plugin: 'com.github.mlangc.jmhreport'

apply from: rootProject.file('jmh.gradle')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
    }
}

dependencies {
    implementation 'com.google.guava:guava:19.0'

    kaptJmh 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}

jmhReport {
    jmhResultPath = project.file('build/reports/jmh/result.json')
    jmhReportOutput = project.file('build/reports/jmh')
}

tasks.jmh.finalizedBy tasks.jmhReport
