apply plugin: 'java'
apply plugin: 'io.github.mlangc.jmhreport'

apply from: rootProject.file('jmh.gradle')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation 'com.google.guava:guava:19.0'
    implementation 'com.jakewharton.byteunits:byteunits:0.9.1'

    implementation 'org.apache.hadoop:hadoop-common:2.6.0'
    implementation 'org.apache.hadoop:hadoop-hdfs:2.6.0'

    implementation 'com.yahoo.datasketches:memory:0.8.4'

    jmhImplementation 'org.assertj:assertj-core:3.27.7'
}

jmhReport {
    jmhResultPath = project.file('build/reports/jmh/result.json')
    jmhReportOutput = project.file('build/reports/jmh')
}

tasks.jmh.finalizedBy tasks.jmhReport
