/**
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.morethan.jmhreport.gradle.task;

import io.morethan.jmhreport.Extensions;
import io.morethan.jmhreport.gradle.JmhReportExtension;
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;
import org.gradle.util.GradleVersion;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.zip.ZipInputStream;

/**
 * Task for generating a jmh-report from the default report location (configured through JmhReportExtension)
 **/
public class JmhReportTask extends DefaultTask {

    //TODO declare input as input
    @TaskAction
    public void generateReport() throws IOException {
        GradleVersion gradleVersion = GradleVersion.current();

        if (gradleVersion.compareTo(GradleVersion.version("8.0")) < 0) {
            getLogger().warn("This plugin doesn't support gradle versions < 8.0; it might still work, but you are on your own.");
        }

        JmhReportExtension extension = getProject().getExtensions().getByType(JmhReportExtension.class);
        // project.file resolves relative paths against the project directory (and takes File as well as String)
        File reportFile = getProject().file(requireNonNull(extension.getJmhResultPath(), "jmhResultPath must not be null"));
        File outputFolder = getProject().file(requireNonNull(extension.getJmhReportOutput(), "jmhReportOutput must not be null"));

        if (!reportFile.exists()) {
            throw new IllegalStateException("Input '" + reportFile.getCanonicalFile() + "' does not exists!");
        }

        try (InputStream jmhVisualizerZip = getClass().getResourceAsStream("/jmh-visualizer.zip");
             ZipInputStream zipStream = new ZipInputStream(jmhVisualizerZip)) {
            Extensions.extract(zipStream, outputFolder);
        }

        String runName = removeExtension(reportFile.getName());
        File providedJsFile = new File(outputFolder, "provided.js");
        try (PrintWriter writer = new PrintWriter(providedJsFile, "UTF-8")) {
            writer.println("// provided.js - generated by gradle-jmh-report, "
                    + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS", Locale.getDefault()).format(new Date()));
            writer.println();
            writer.println("var providedBenchmarks = ['" + runName + "'];");
            writer.println();
            writer.println("var providedBenchmarkStore = {");
            writer.println("'" + runName + "': ");
            try (BufferedReader reader = Files.newBufferedReader(reportFile.toPath(), StandardCharsets.UTF_8)) {
                String line;
                while ((line = reader.readLine()) != null) {
                    writer.println(line);
                }
            }
            writer.println("};");
        }
        System.out.println("JMH Report generated, please open: file://" + outputFolder + "/index.html");
    }

    private static String requireNonNull(String value, String message) {
        if (value == null) {
            throw new IllegalStateException(message);
        }
        return value;
    }

    private static String removeExtension(String fileName) {
        int dot = fileName.lastIndexOf('.');
        return dot < 0 ? fileName : fileName.substring(0, dot);
    }
}
