apply plugin: 'io.github.mlangc.jmhreport'

jmhReport {
    jmhResultPath = project.file('build/reports/jmh/results.json')
    jmhReportOutput = project.file('build/reports/jmh')
}

// Subclasses of JmhReportTask have to keep working; only myReport is supposed to produce the report here
class MyReportTask extends io.github.mlangc.jmhreport.gradle.task.JmhReportTask {}

tasks.named('jmhReport') { enabled = false }
tasks.register('myReport', MyReportTask)
